# -*- coding: utf-8 -*-
"""Budget_Planner_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M4T7j4JOQzY-n-ZE-x1KzOQsr8EIJsHU
"""

#This is the welcome message
print("Welcome to your Travel Budget Tracker!")
print("******")

#Categories defines all the things we are tracking within the planner
categories=["Travel expences", "Accomodation expences", "Excursion expences", "Food expences", "Miscellaneous"]

#Dictionaries hold each of the amounts and the lists will hold the category names where overspending or saving is seen
budget={}
spending={}
saving={}
ov=[]
s=[]

#The amounts are being stored for each category in the dictionary
print()
print("Please enter your decided total budget for each categories:")
print()
print()
for i in categories:
  budget[i]=float(input(i + " in rupees: "))  #This stores each total value of budget
  print()

print()
print()

print("Please enter your total spending for each categories:")
print()
print()
for j in categories:
  spending[j]=float(input(j + " in rupees: ")) #This stores each total value of spending
  print()

#Each sum of budget, spending, savings and over spending according to category is saved here respectively
total_budget=sum(budget.values())
total_spending=sum(spending.values())
total_savings=0
total_ov=0


#Here we compare the budgets with the spendings
print()
print("******")
print()
print("Here is a comparison of your budget and spendings for each category: ")
print()
print()

for category in budget:
  difference=spending[category]-budget[category] #the difference tells if we are above or below budget
  print(category + ":\nBudgeted: Rs.", str(budget[category]) + "\nSpent: Rs." + str(spending[category]))

  #This if-elif-else statement is helping us determine and print if the user has spent extra in the category or not
  if difference>0:
    total_ov=total_ov+difference
    print("You have spent Rs." + str(difference) + " extra on "+ category + ".")
    ov.append(category) #Categories where overspending has been done is saved in the list
    print()
  elif difference<0:
    sv=difference*-1
    saving[category]=sv
    total_savings=total_savings+saving[category]
    print("You have saved Rs." + str(saving[category]) + " on "+ category +".")
    s.append(category) #Categories where saving has been done is saved in the list
    print()
  else:
    print("You have spent your full budgeted money for "+category+".")
    print()

#Here we are printing the final observations
print()
print("*****")
print()
print("Your spendings and savings can be seen as:")
print()
print("Your total overspending across categories was: Rs.", total_ov) #gives a sum of money gone beyond budget
print("Your total savings across categories was: Rs.", total_savings) #gives a sum of money under budget
print()
print()
print("Your total budget was: ", total_budget) #gives a sum of total budget
print("Total spendings were: ", total_spending) #gives a sum of total spending, keeping in mind where the money has been above or below budget
print()
print()
print("Hence:")
print()

td=total_spending-total_budget #This gives us the money saved or extra spent
if td>0:
  print("You have gone over your total budget of Rs. ", total_budget, " by Rs. ", td) #This prints the total extra spending
  print("Please consider cutting your expences, especially in ", ov) #This prints the categories where extra spending was done
elif td<0:
  print("You have stayed under your budget of Rs. ", total_budget, " and saved Rs. ", -td) #This prints the total saving
  print("You have saved well in ", s) #This prints the categories where saving was done
else:
  print("You have spent your budget of Rs. ", total_budget)
  print("good job!")

#concluding message
print()
print("*****")
print()
print("Thank you for using our budget planner!")